# Generated by Django 5.0.4 on 2024-05-04 16:33

import libraryManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='returnDate',
            field=models.DateTimeField(default=libraryManager.models.make_return_date),
        ),
    ]
