# Generated by Django 5.0.4 on 2024-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManager', '0002_alter_borrowedbook_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numBorrowedCopies',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
