# Generated by Django 5.0.4 on 2024-05-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManager', '0003_alter_book_numborrowedcopies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='numBorrowedCopies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='numCopies',
        ),
        migrations.AddField(
            model_name='book',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
