if (!localStorage.getItem("books")) {
  const books = [
    {
      title: "Trouble fight turn.",
      author: "Amber Salazar",
      rating: 3.4,
      image: "https://placehold.co/100x150",
      story:
        "Light end top. Thing game effect people. Industry parent blood stuff. Child head us make would response walk. Standard within new cause. Small game point war night current different. Economic middle hot. Hospital but room themselves past consider. Manager miss buy project front process. Better beat trial there. Like against speak form network feel. Age successful reveal policy. Memory modern factor which one.",
      categories: ["adventure", "fantasy"],
      "date-added": 1683068153393,
      "date-published": "2023-01-30",
      availability: true,
      id: 1,
    },
    {
      title: "Heart growth.",
      author: "Elijah Johnson",
      rating: 0.4,
      image: "https://placehold.co/100x150",
      story:
        "This yard discover late could. Red note like direction cold early. Morning window southern speech. Mother church dream country. Population movie eye result financial. First shake try usually administration. House sea change environmental firm effort commercial blood. Return will think. Them relationship option able firm again. Management study have ground within listen behavior. Career election before save rest fact inside. Culture town admit population theory present.",
      categories: ["horror", "fantasy"],
      "date-added": 1686167579298,
      "date-published": "2014-05-19",
      availability: true,
      id: 2,
    },
    {
      title: "Nor listen.",
      author: "Kristen Lewis",
      rating: 1.8,
      image: "https://placehold.co/100x150",
      story:
        "Huge fine rest firm cover American. If exactly high off court add. Appear available certainly hotel fall. Meeting because program pass. Allow leave tonight consider shoulder respond represent material. Power lose girl of fire husband car. Last less capital eat case audience.",
      categories: ["mystery", "fantasy"],
      "date-added": 1686415717079,
      "date-published": "2010-05-25",
      availability: false,
      id: 3,
    },
    {
      title: "Near sense particularly.",
      author: "Dominic Gomez",
      rating: 4.3,
      image: "https://placehold.co/100x150",
      story:
        "Issue call discuss position. Huge end our. Data page phone. People project another process religious several. Class cut none compare. End where assume Republican.",
      categories: ["fantasy", "horror"],
      "date-added": 1689405144004,
      "date-published": "2015-12-13",
      availability: false,
      id: 4,
    },
    {
      title: "Space guess until.",
      author: "John Thompson",
      rating: 4.6,
      image: "https://placehold.co/100x150",
      story:
        "Animal baby significant culture project tough drug. Opportunity civil animal sit detail unit information thousand. Tax girl house wall soldier. Worker stuff clear north take. Support true different day store consumer. Start reason huge oil arrive example. Operation their class agree together two back sit. Try time officer economy draw. Impact evening certain usually. Respond design then travel state design top night. Edge election purpose environment. Join particularly grow everyone more within offer. Yourself lot public chance form degree rate.",
      categories: ["horror", "adventure"],
      "date-added": 1689744596770,
      "date-published": "2005-04-15",
      availability: false,
      id: 5,
    },
    {
      title: "With.",
      author: "Jaime Young",
      rating: 1.8,
      image: "https://placehold.co/100x150",
      story:
        "Owner imagine across fine nor think the. Without benefit staff population sea. Quite by move something. Prove issue source. Agreement good hot safe piece wish main. Office wear use answer central trip. Line heart down concern drop show work. Open age you plan bank seven among individual. Opportunity thing population central event. Goal hour first put us six of. Add country line decide. Cultural fill culture leave kind.",
      categories: ["adventure", "mystery"],
      "date-added": 1689761528029,
      "date-published": "2018-01-26",
      availability: true,
      id: 6,
    },
    {
      title: "Kitchen first discussion.",
      author: "Roberto Morales",
      rating: 1.6,
      image: "https://placehold.co/100x150",
      story:
        "Write different month address yard address. Item short number hope message. Paper manage will together. Politics human become today television report capital. Learn hour upon young move think. Benefit ready ever protect. Great but yet between. Discover learn fund time capital professor trip similar. Standard station account stand sense.",
      categories: ["adventure", "horror"],
      "date-added": 1691083124169,
      "date-published": "2011-12-09",
      availability: true,
      id: 7,
    },
    {
      title: "Southern education high.",
      author: "Carolyn Vargas",
      rating: 3.8,
      image: "https://placehold.co/100x150",
      story:
        "Sometimes reach person what current institution. Above can five. Assume any occur stop. As same beat attention where. Child draw majority interview hear upon admit medical. Write accept cause above cultural listen this. Detail bill baby front same entire people. Late or study inside. Stuff trip decade production. Simply term price player. Able record word include to give thing service. Happy growth top here action.",
      categories: ["mystery", "fantasy"],
      "date-added": 1691331298250,
      "date-published": "2021-07-19",
      availability: false,
      id: 8,
    },
    {
      title: "Expect.",
      author: "Tracy Frost",
      rating: 3.6,
      image: "https://placehold.co/100x150",
      story:
        "Political can director still. Character conference number would. Police later suddenly energy need. Really hit eye break Democrat street. Music training deep final eye point. Reduce ask customer baby walk. Table allow energy region best remain. Purpose crime raise commercial education degree event.",
      categories: ["mystery", "horror"],
      "date-added": 1691343877592,
      "date-published": "2011-12-26",
      availability: true,
      id: 9,
    },
    {
      title: "Best she paper.",
      author: "Brenda Thomas",
      rating: 0.7,
      image: "https://placehold.co/100x150",
      story:
        "Result town visit so. Raise third tell response coach after. Modern remain visit glass economy democratic sport. Star traditional activity someone. People economic art remain. True something letter civil author expect. Partner half some crime significant institution simply. Radio discussion own senior give. Material home field development. Win ground heart rather. Finish floor teach two. Short another through current reach. Experience firm follow strategy seek house else.",
      categories: ["horror", "adventure"],
      "date-added": 1693452529699,
      "date-published": "2006-06-18",
      availability: false,
      id: 10,
    },
    {
      title: "Fact difficult international.",
      author: "Michael Boyd",
      rating: 0.7,
      image: "https://placehold.co/100x150",
      story:
        "Ever music second billion growth most past bed. Red involve team thing believe. Every environmental think enter. Most similar station test. Follow three series top. Record particular because those hotel century. Popular go father company practice again of experience.",
      categories: ["fantasy", "horror"],
      "date-added": 1693799205236,
      "date-published": "2012-01-30",
      availability: false,
      id: 11,
    },
    {
      title: "Glass try child.",
      author: "Christopher Martinez",
      rating: 0.3,
      image: "https://placehold.co/100x150",
      story:
        "Soldier figure several test. Evening offer visit can mind instead out. List resource out part student should already. Career people country free. Present fund institution blue could. Fast stop image at his.",
      categories: ["adventure", "fantasy"],
      "date-added": 1694853397587,
      "date-published": "2017-12-02",
      availability: false,
      id: 12,
    },
    {
      title: "Explain.",
      author: "Sharon Thomas",
      rating: 0.7,
      image: "https://placehold.co/100x150",
      story:
        "Can man child friend black age. Herself majority former attention lot quite middle. Word upon artist maybe true of maybe road. Although stage admit best two fire federal rather. Size gun difference our effort know benefit attention. Change next onto theory note oil tough. Nearly game ten international success suggest. Able share significant allow address. Yet view will life see American. Mother trouble change cause idea sing style Mr. Drive which together reach address.",
      categories: ["fantasy", "horror"],
      "date-added": 1696183537571,
      "date-published": "2006-01-17",
      availability: true,
      id: 13,
    },
    {
      title: "Movement though organization.",
      author: "Wesley Mccullough",
      rating: 4.8,
      image: "https://placehold.co/100x150",
      story:
        "Worker now medical space wife sea population. Newspaper although theory business pass hotel himself. Year social white star. Eat measure though treatment watch. All watch increase court. Speak news doctor worker. Check nor ball recent force air attack. And clearly building. Arrive tax environment name call action Mrs president. Fire edge cause hand hotel participant market. In mother light voice really well. Never cause herself happen boy. Month society store science kitchen.",
      categories: ["fantasy", "adventure"],
      "date-added": 1696650287569,
      "date-published": "2012-09-09",
      availability: false,
      id: 14,
    },
    {
      title: "Indeed carry.",
      author: "Jose Freeman",
      rating: 0.4,
      image: "https://placehold.co/100x150",
      story:
        "Ball road anything those suffer nor again. Minute great compare Republican. Eight spring their be certain. Player his social describe prevent night standard event. Beat sometimes hotel join recent accept. Wear treatment fight cell fear. Number personal act necessary evening economic. Rich someone they. Doctor organization design. Modern employee remember he speech. Action exist heart around. Behind accept report kid begin challenge soldier. Behind ability pick ten.",
      categories: ["horror", "mystery"],
      "date-added": 1696767478703,
      "date-published": "2013-12-13",
      availability: true,
      id: 15,
    },
    {
      title: "Middle course.",
      author: "Michelle Yang",
      rating: 3.8,
      image: "https://placehold.co/100x150",
      story:
        "Able to blood society daughter cup. Production serve management lose street. Power class especially stay yes home spend. Draw billion art defense most already. Can no individual couple feeling. Create member forward approach try best. Professional get religious number. Center site team owner Mrs. Behavior other run common.",
      categories: ["fantasy", "horror"],
      "date-added": 1697225501476,
      "date-published": "2019-04-02",
      availability: false,
      id: 16,
    },
    {
      title: "Increase science yard.",
      author: "Jessica Jones",
      rating: 4.4,
      image: "https://placehold.co/100x150",
      story:
        "Line finally hundred boy break first. Cover there professional along air. Mention tell teach ball. Somebody law data pattern sea nation rich. Its represent reflect sort. Other term campaign nothing law base. Here growth similar personal. From development thought against peace fly. Entire measure cause image. Must last company position us forward likely pretty. Find scene admit.",
      categories: ["horror", "adventure"],
      "date-added": 1697462043086,
      "date-published": "2005-06-04",
      availability: true,
      id: 17,
    },
    {
      title: "Continue.",
      author: "Lynn Gray",
      rating: 0.3,
      image: "https://placehold.co/100x150",
      story:
        "Agree ok everyone degree first over. Staff soldier catch build. Agency yourself bar toward himself. Clearly police close condition. Several five property already interview maintain successful. Student ever get hair. Detail mention medical very. Inside news attorney thousand. Because on loss wonder bar.",
      categories: ["fantasy", "horror"],
      "date-added": 1700525297792,
      "date-published": "2002-11-11",
      availability: false,
      id: 18,
    },
    {
      title: "Will even.",
      author: "Amy Fernandez",
      rating: 2.5,
      image: "https://placehold.co/100x150",
      story:
        "Point public include. Movement off such raise of test medical. Sound whom tree they type network. Their lot million perform. Believe simply trip up too. Performance laugh play accept. Particularly party rather series. Deal evening our television truth. Customer though guess avoid.",
      categories: ["fantasy", "horror"],
      "date-added": 1700905570216,
      "date-published": "2019-09-28",
      availability: true,
      id: 19,
    },
    {
      title: "Across list child.",
      author: "Ronald Jarvis",
      rating: 5.0,
      image: "https://placehold.co/100x150",
      story:
        "Store mention computer figure animal hair ever. Carry whether nothing campaign some shake. Act remain every professional nor. Change fund bring successful what air. Office discussion activity hot accept. Participant item prove. Character four film course. Back student order education door where. Take serve effort pick. Agent it term. Her include draw idea everybody.",
      categories: ["mystery", "adventure"],
      "date-added": 1702779635672,
      "date-published": "2004-07-16",
      availability: true,
      id: 20,
    },
    {
      title: "Unit car officer.",
      author: "Daniel Campbell",
      rating: 4.4,
      image: "https://placehold.co/100x150",
      story:
        "Citizen word spend result government statement new. Report physical grow form hear turn onto. Center play hope allow. Small someone firm available attack his. Property think require film chair enjoy final. West rather environmental piece upon positive conference. Up marriage possible hair at suffer main. Word cold onto enjoy sort wind. Reach song customer their. Sign send case forward.",
      categories: ["mystery", "fantasy"],
      "date-added": 1706115906426,
      "date-published": "2003-12-29",
      availability: true,
      id: 21,
    },
    {
      title: "Anyone amount.",
      author: "Aimee Abbott",
      rating: 2.1,
      image: "https://placehold.co/100x150",
      story:
        "Entire kitchen thousand sister fear push. Meet base design accept first. Hotel city music few allow hair. Republican plan will strategy. However film walk. Send test identify happen themselves country. Soldier speech avoid design American shoulder. Quality then my figure training method all. Who company guess save perhaps to whether. Cold measure special medical. Floor work clear set offer reality officer. Hundred center mouth court can provide. Foot practice near president.",
      categories: ["fantasy", "adventure"],
      "date-added": 1706903781243,
      "date-published": "2008-12-20",
      availability: false,
      id: 22,
    },
    {
      title: "Attack power actually.",
      author: "Andrew Cherry",
      rating: 4.4,
      image: "https://placehold.co/100x150",
      story:
        "Go camera development hope Congress. Such state peace. Share enter including nation long image wide. Production south cultural but. Chair floor economic Democrat easy accept heart. Republican worker drop push fall market nature. Full southern enjoy me money response according. Certainly civil fast own. Guess sell think head option push occur. Campaign chair crime should kitchen man. Stop too offer miss organization push religious. Situation always ten stock part.",
      categories: ["horror", "fantasy"],
      "date-added": 1707359246029,
      "date-published": "2000-05-26",
      availability: false,
      id: 23,
    },
    {
      title: "Choice edge public.",
      author: "Andrea Lawson",
      rating: 2.7,
      image: "https://placehold.co/100x150",
      story:
        "Medical feel thing fear. Attention sport left month. New born employee face event sort never water. Concern eat establish machine shoulder short trouble drop. First carry appear two thus friend. Low democratic type wait play least. Rock good great by. Word minute sound feel. Simply behind worker husband analysis relationship.",
      categories: ["mystery", "adventure"],
      "date-added": 1708171626434,
      "date-published": "2020-12-12",
      availability: true,
      id: 24,
    },
    {
      title: "Ability Mrs believe.",
      author: "Brandon Carter",
      rating: 4.2,
      image: "https://placehold.co/100x150",
      story:
        "More scene catch bad anyone. Main action sense. Security learn water share. Responsibility high certain. Eight paper wall. Trouble behavior article where land style.",
      categories: ["mystery", "fantasy"],
      "date-added": 1711945478235,
      "date-published": "2007-08-08",
      availability: true,
      id: 25,
    },
  ];

  localStorage.setItem("books", JSON.stringify(books));
}
