if (!localStorage.getItem("books")) {
  const books = [
    {
      title: "Road agent.",
      author: "Latoya Little",
      rating: 1.8,
      image: "https://placehold.co/100x150",
      story:
        "Billion surface mission government human themselves. Easy card what fill medical. Behavior seven report. Become everything yes. Measure better bit avoid strong sound. Choose sort reduce without whole guess. Dream reflect much key nature bag pay. Husband voice career pay help.",
      categories: ["horror", "mystery"],
      "date-added": 1682260465774,
      "date-published": "2004-02-02",
      availability: false,
      reviews: [],
      id: 1,
    },
    {
      title: "Pay drop.",
      author: "Charles Cline",
      rating: 1.6,
      image: "https://placehold.co/100x150",
      story:
        "More sound rest attack left. Find glass from idea expect himself two. Grow stuff without should energy. Surface power vote free eight office. Again car use quickly value. Middle never central main. Soon stuff unit rate leave. Later you clear computer forget. Success score bed sport speech grow line. Production method budget compare I. Interview true occur late middle.",
      categories: ["horror", "adventure"],
      "date-added": 1683249864716,
      "date-published": "2003-04-14",
      availability: false,
      reviews: [],
      id: 2,
    },
    {
      title: "Most perhaps decade.",
      author: "Amy Rivera",
      rating: 3.7,
      image: "https://placehold.co/100x150",
      story:
        "Drop may loss maybe feeling fast experience. Value fact trouble around service own a others. Trouble my not cause relate color on will. Second stage day almost. Artist story subject other. Short couple bit course long toward life. Hot century too month race through fish. Amount he way ask to exactly how. Better stand kind current range school seem.",
      categories: ["horror", "fantasy"],
      "date-added": 1684716541516,
      "date-published": "2020-06-02",
      availability: true,
      reviews: [],
      id: 3,
    },
    {
      title: "Focus high they.",
      author: "Steven Grant",
      rating: 4.5,
      image: "https://placehold.co/100x150",
      story:
        "Though toward avoid. Wall maybe either remember. Section cell never from study. Political learn politics product first tonight perhaps. Including well including environment take to. Room hit weight almost beyond single. Sense question it approach despite born finally. Start allow report eat everyone produce end might. Relationship cause risk able natural cut population. See production energy machine day.",
      categories: ["mystery", "adventure"],
      "date-added": 1685661256135,
      "date-published": "2020-06-05",
      availability: true,
      reviews: [],
      id: 4,
    },
    {
      title: "Success industry force.",
      author: "Richard Robbins",
      rating: 2.2,
      image: "https://placehold.co/100x150",
      story:
        "Out fine cut there who. Administration decide try budget stay four. Whatever finally or bad. Store apply win. Miss arm approach build energy. Research question whom tend main.",
      categories: ["adventure", "mystery"],
      "date-added": 1685994071439,
      "date-published": "2023-04-30",
      availability: true,
      reviews: [],
      id: 5,
    },
    {
      title: "Want drop finish.",
      author: "Theodore Johnson",
      rating: 4.8,
      image: "https://placehold.co/100x150",
      story:
        "Prepare responsibility just certain may. Attorney tree leg role. Under feeling probably condition knowledge. Should paper attention. At program finish area need. Field majority eight lay probably answer message. Kitchen face out wonder party production right. Nation provide able key both upon instead people. Detail chance weight treat worker various. Old deep language onto her now investment. Business far member knowledge interesting break.",
      categories: ["horror", "fantasy"],
      "date-added": 1687782307823,
      "date-published": "2015-06-22",
      availability: true,
      reviews: [],
      id: 6,
    },
    {
      title: "Help.",
      author: "Joshua Thomas",
      rating: 3.4,
      image: "https://placehold.co/100x150",
      story:
        "Establish word investment ability artist sense. Per now but book yard age. Activity relate specific whose various for find if. History large including bill officer through. Someone half subject play available. Boy consider employee church remain summer.",
      categories: ["fantasy", "adventure"],
      "date-added": 1688351893001,
      "date-published": "2004-11-07",
      availability: false,
      reviews: [],
      id: 7,
    },
    {
      title: "Military seek next.",
      author: "Albert Jones",
      rating: 5.0,
      image: "https://placehold.co/100x150",
      story:
        "Food will network however. Live ready which or. Bank son white hard base president argue. Up must such democratic above if. Thought recent answer cold face. Remain truth piece light show. Learn beautiful growth hard fall subject concern. Probably tree maintain begin Mrs expect.",
      categories: ["adventure", "horror"],
      "date-added": 1690000549260,
      "date-published": "2018-04-19",
      availability: false,
      reviews: [],
      id: 8,
    },
    {
      title: "Cause region find.",
      author: "Cole Pena",
      rating: 0.0,
      image: "https://placehold.co/100x150",
      story:
        "Main by local push choice happy. Staff lead Democrat physical southern modern practice health. Morning near of alone cold computer friend item. Item impact politics create. Medical white like trade fish main few. Administration change debate base among term. Brother enjoy series option then box camera. Catch crime player show myself.",
      categories: ["horror", "adventure"],
      "date-added": 1692472673127,
      "date-published": "2022-04-09",
      availability: true,
      reviews: [],
      id: 9,
    },
    {
      title: "Water sure then.",
      author: "Shannon Mcmillan",
      rating: 2.6,
      image: "https://placehold.co/100x150",
      story:
        "Six morning hour fine already. Let big my field teacher. Thus impact suddenly become media. Training agreement face. Project seven speech need practice smile college. Analysis nor sometimes instead enjoy be but professional. Exactly value suddenly. Loss another resource human. Fill fast job check. Professional without give beautiful expert hot.",
      categories: ["horror", "mystery"],
      "date-added": 1695676547258,
      "date-published": "2022-07-14",
      availability: false,
      reviews: [],
      id: 10,
    },
    {
      title: "Walk dog.",
      author: "Shelley Moore",
      rating: 2.3,
      image: "https://placehold.co/100x150",
      story:
        "Size find experience also right blue. Effect box space future authority relate lose. Democratic space what. Writer set daughter me three door. Always consumer quickly a power group citizen. Another social those far there. Approach country thank available.",
      categories: ["adventure", "fantasy"],
      "date-added": 1695758340436,
      "date-published": "2023-02-04",
      availability: false,
      reviews: [],
      id: 11,
    },
    {
      title: "Decide Democrat majority.",
      author: "Linda Hayes",
      rating: 3.8,
      image: "https://placehold.co/100x150",
      story:
        "Six himself policy American certainly a choose. Seven direction community find. History while start sound listen join town. Eye PM magazine again. Turn act official energy particular off catch. Matter nature prevent Mrs role. Likely southern report possible wear seem bring. Against here create learn generation develop or. Project tax compare treatment subject. After look drive five full.",
      categories: ["adventure", "fantasy"],
      "date-added": 1696877301909,
      "date-published": "2021-09-18",
      availability: true,
      reviews: [],
      id: 12,
    },
    {
      title: "Training term event.",
      author: "Riley West",
      rating: 4.0,
      image: "https://placehold.co/100x150",
      story:
        "Huge concern magazine threat. Into interesting her method. Company tell partner hour. Center himself staff garden prevent different such lot. Only spend bag during sort structure. Section game nothing person protect prove somebody. Contain realize president sit small market dog.",
      categories: ["fantasy", "horror"],
      "date-added": 1697317477968,
      "date-published": "2022-09-23",
      availability: true,
      reviews: [],
      id: 13,
    },
    {
      title: "Ground budget oil when.",
      author: "David Mitchell",
      rating: 1.2,
      image: "https://placehold.co/100x150",
      story:
        "Term Democrat share image head arm then. Manager fear religious baby deal firm. Industry husband us summer last anything next. Mean example listen drive none next suffer last. Sing line window society place rest. Loss grow check add public pressure yeah. Start good better pressure. Where seven where street.",
      categories: ["adventure", "fantasy"],
      "date-added": 1699387143903,
      "date-published": "2000-05-28",
      availability: false,
      reviews: [],
      id: 14,
    },
    {
      title: "Suggest.",
      author: "Ricky Weaver",
      rating: 4.8,
      image: "https://placehold.co/100x150",
      story:
        "Training answer explain physical notice. Professor year certain serious field some spend. Make prove bar full teach write. Senior generation tell short. Inside partner small million big charge. Among behind performance support thing so. Include development he moment PM. Create popular letter political. Baby lose own shake parent security prevent.",
      categories: ["fantasy", "horror"],
      "date-added": 1700357415654,
      "date-published": "2013-11-22",
      availability: false,
      reviews: [],
      id: 15,
    },
    {
      title: "Prepare environmental term.",
      author: "Mrs. Diane Jimenez",
      rating: 2.3,
      image: "https://placehold.co/100x150",
      story:
        "Play without base almost rise. Collection alone be decade line scientist both control. Wide happen move world perhaps. Lot star risk which particularly. Everybody she kind step. Send consumer catch husband challenge get. For stop summer whether your no vote. Marriage adult management star store anything effort. West cost she expect adult how wait.",
      categories: ["fantasy", "mystery"],
      "date-added": 1700885960216,
      "date-published": "2023-12-16",
      availability: false,
      reviews: [],
      id: 16,
    },
    {
      title: "Range or arrive.",
      author: "Mackenzie Sullivan",
      rating: 3.2,
      image: "https://placehold.co/100x150",
      story:
        "Whom about owner check writer. Production myself would. Low professor president environment. Authority painting agree head condition impact something. Week write growth subject. Include method worker box partner little person. Light across keep ball property security off. Perhaps down statement challenge protect both. Computer try matter number.",
      categories: ["horror", "adventure"],
      "date-added": 1702040841010,
      "date-published": "2020-12-31",
      availability: false,
      reviews: [],
      id: 17,
    },
    {
      title: "Cost body follow.",
      author: "Angela Brandt",
      rating: 2.4,
      image: "https://placehold.co/100x150",
      story:
        "Safe public national Democrat. Address store source get rule certain. Thought talk sing music majority. Mrs energy present. Pattern conference tend management white. Throughout tell hair race challenge listen. Discover author whether executive know single remember think. Whom politics break decision either big. Every difficult that modern together address. Very place edge drug image since. Card look above information statement real.",
      categories: ["adventure", "horror"],
      "date-added": 1703003131380,
      "date-published": "2021-11-16",
      availability: false,
      reviews: [],
      id: 18,
    },
    {
      title: "Painting social.",
      author: "Michael Hays",
      rating: 0.7,
      image: "https://placehold.co/100x150",
      story:
        "Also never hear out. System report sea ok. Miss cold start year. Yeah response management wife approach environment. Service above theory dream health generation wrong. Will option inside professor. Bit both expect level debate ahead continue security. However part well decade million public. Away part likely hotel deep. Evening indicate role car. Nor their both increase writer study religious. Class realize represent pressure. None show magazine year candidate pick debate.",
      categories: ["adventure", "fantasy"],
      "date-added": 1703638204720,
      "date-published": "2013-03-26",
      availability: true,
      reviews: [],
      id: 19,
    },
    {
      title: "As behavior.",
      author: "Daniel Holden",
      rating: 2.1,
      image: "https://placehold.co/100x150",
      story:
        "Reach maintain here structure. Team growth art mouth. Speak employee eye white yes. Friend group need environment word act. President visit difference ask how list. Owner people project them arrive find baby. Inside out agreement require source group. Not market far sort couple government.",
      categories: ["horror", "adventure"],
      "date-added": 1707776560154,
      "date-published": "2008-07-13",
      availability: false,
      reviews: [],
      id: 20,
    },
    {
      title: "See piece special.",
      author: "Phillip Walton",
      rating: 0.5,
      image: "https://placehold.co/100x150",
      story:
        "Fear before half rule. Could air everything. As to wall near real not house. Bed parent surface pull. Account only around nearly authority. Democrat maintain three forget. Author sing girl hand.",
      categories: ["fantasy", "adventure"],
      "date-added": 1707825637600,
      "date-published": "2014-06-27",
      availability: true,
      reviews: [],
      id: 21,
    },
    {
      title: "Take direction since evening.",
      author: "Tim Carter",
      rating: 0.7,
      image: "https://placehold.co/100x150",
      story:
        "Game exactly under act ground candidate throughout hour. Least human lawyer throw reduce. Responsibility under major. Each small include join about matter soldier. Remember look will feel personal fish charge drop. Plant send total. Major open hope. Win media must nation leg big. Statement effect best project respond. Pass seven available understand word exist manage scene. Stand seven reality sing imagine treat.",
      categories: ["fantasy", "horror"],
      "date-added": 1709090201505,
      "date-published": "2013-08-31",
      availability: true,
      reviews: [],
      id: 22,
    },
    {
      title: "College line.",
      author: "Julie Calhoun",
      rating: 3.5,
      image: "https://placehold.co/100x150",
      story:
        "Wife remember against stage talk and help. Around everybody medical customer. Still serve benefit research cut. Yes upon nor computer body even. A over poor room. Eat myself lawyer media.",
      categories: ["adventure", "horror"],
      "date-added": 1712242761370,
      "date-published": "2008-03-28",
      availability: false,
      reviews: [],
      id: 23,
    },
    {
      title: "Those picture radio result.",
      author: "Wendy Roach",
      rating: 4.7,
      image: "https://placehold.co/100x150",
      story:
        "Development matter cell thought gas. Way material myself forward exactly tell. Hold camera deep. Player hundred open big industry doctor forward. Source this source number. Way back alone imagine truth kind brother. Finally top though big kid speech. Matter bar out who newspaper wall man. Amount space land worry yard choose.",
      categories: ["horror", "adventure"],
      "date-added": 1712325463257,
      "date-published": "2008-07-05",
      availability: false,
      reviews: [],
      id: 24,
    },
    {
      title: "Glass brother way.",
      author: "Tammy Allen",
      rating: 2.6,
      image: "https://placehold.co/100x150",
      story:
        "Painting guy still. South so couple ready election new. Artist senior tell area source age land mission. Can effect good tree thought. Old glass tend whether life. Really into same. Analysis house left and enter language. Share news quickly. Then first thus gun give show.",
      categories: ["horror", "fantasy"],
      "date-added": 1713619176448,
      "date-published": "2008-08-05",
      availability: false,
      reviews: [],
      id: 25,
    },
  ];

  localStorage.setItem("books", JSON.stringify(books));
}
